function onload(save_state)
    local button_parameters = {}
    button_parameters.function_owner = self
    button_parameters.label = ""
    button_parameters.height = 700
    button_parameters.width = 1000
    button_parameters.color = {0, 0, 0, 0}
    button_parameters.click_function = "sealClicked"
    button_parameters.position = {0, 0, 0.8}
    self.createButton(button_parameters)
end

function sealClicked()
  getObjectFromGUID(Global.getTable("boards").map).call("unseal")
end